name: Feature request
description: Propose a new capability or improvement.
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What workflow or pain point should be improved?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your proposed behavior.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
  - type: textarea
    id: impact
    attributes:
      label: Security and data impact
      description: Note any impact on offline policy, crypto/storage model, or release integrity.
    validations:
      required: false
